export { default as HomeContainer } from './HomeContainer'
export { default as StartupContainer } from './StartupContainer'
export { default as OnBoardingScreen } from './OnBoardingScreen'
export { default as Login } from './Login'
export {default as ForgetPassword} from './ForgetPassword'
export {default as SignUpScreen} from './SignUpScreen'
export {default as PhoneVerification} from './PhoneVerification'
export {default as OTPScreen} from './OTPScreen'
export {default as TestScreen} from './Test/TestScreen'
export {default as VideoScreen} from './VideoScreen'
export {default as SubjectScreen} from './Subjects/SubjectScreen'
export {default as ChapterScreen} from './Subjects/Chapters/ChapterScreen'
export {default as Setting} from './Setting'
export {default as PurchaseDetails} from './Payment/PurchaseDetails'
export {default as SelectClassAndBoard} from './SelectClassAndBoard'
export {default as SelectPreparation} from './SelectPreparation'
export {default as AnalysisScreen} from './Analysis/AnalysisReport'
export {default as MyProfileScreen} from './MyProfile'
export {default as EnterForgotPassword} from './EnterForgotPassword'

